/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickMatchRouteImport } from './routes/quick-match'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryIndexRouteImport } from './routes/registry.index'
import { Route as CourtsIndexRouteImport } from './routes/courts.index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as CourtsCourtSlugRouteImport } from './routes/courts.$courtSlug'

const QuickMatchRoute = QuickMatchRouteImport.update({
  id: '/quick-match',
  path: '/quick-match',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsIndexRoute = CourtsIndexRouteImport.update({
  id: '/courts/',
  path: '/courts/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsCourtSlugRoute = CourtsCourtSlugRouteImport.update({
  id: '/courts/$courtSlug',
  path: '/courts/$courtSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quick-match': typeof QuickMatchRoute
  '/courts/$courtSlug': typeof CourtsCourtSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts/': typeof CourtsIndexRoute
  '/registry/': typeof RegistryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quick-match': typeof QuickMatchRoute
  '/courts/$courtSlug': typeof CourtsCourtSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts': typeof CourtsIndexRoute
  '/registry': typeof RegistryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quick-match': typeof QuickMatchRoute
  '/courts/$courtSlug': typeof CourtsCourtSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts/': typeof CourtsIndexRoute
  '/registry/': typeof RegistryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quick-match'
    | '/courts/$courtSlug'
    | '/match/$matchId'
    | '/courts/'
    | '/registry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quick-match'
    | '/courts/$courtSlug'
    | '/match/$matchId'
    | '/courts'
    | '/registry'
  id:
    | '__root__'
    | '/'
    | '/quick-match'
    | '/courts/$courtSlug'
    | '/match/$matchId'
    | '/courts/'
    | '/registry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuickMatchRoute: typeof QuickMatchRoute
  CourtsCourtSlugRoute: typeof CourtsCourtSlugRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  CourtsIndexRoute: typeof CourtsIndexRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick-match': {
      id: '/quick-match'
      path: '/quick-match'
      fullPath: '/quick-match'
      preLoaderRoute: typeof QuickMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/': {
      id: '/courts/'
      path: '/courts'
      fullPath: '/courts/'
      preLoaderRoute: typeof CourtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$courtSlug': {
      id: '/courts/$courtSlug'
      path: '/courts/$courtSlug'
      fullPath: '/courts/$courtSlug'
      preLoaderRoute: typeof CourtsCourtSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuickMatchRoute: QuickMatchRoute,
  CourtsCourtSlugRoute: CourtsCourtSlugRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  CourtsIndexRoute: CourtsIndexRoute,
  RegistryIndexRoute: RegistryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
