/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourtsIndexRouteImport } from './routes/courts.index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as CourtsCourtSlugRouteImport } from './routes/courts.$courtSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsIndexRoute = CourtsIndexRouteImport.update({
  id: '/courts/',
  path: '/courts/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsCourtSlugRoute = CourtsCourtSlugRouteImport.update({
  id: '/courts/$courtSlug',
  path: '/courts/$courtSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courts/$courtSlug': typeof CourtsCourtSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts/': typeof CourtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courts/$courtSlug': typeof CourtsCourtSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts': typeof CourtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courts/$courtSlug': typeof CourtsCourtSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts/': typeof CourtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/courts/$courtSlug' | '/match/$matchId' | '/courts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courts/$courtSlug' | '/match/$matchId' | '/courts'
  id: '__root__' | '/' | '/courts/$courtSlug' | '/match/$matchId' | '/courts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourtsCourtSlugRoute: typeof CourtsCourtSlugRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  CourtsIndexRoute: typeof CourtsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/': {
      id: '/courts/'
      path: '/courts'
      fullPath: '/courts/'
      preLoaderRoute: typeof CourtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$courtSlug': {
      id: '/courts/$courtSlug'
      path: '/courts/$courtSlug'
      fullPath: '/courts/$courtSlug'
      preLoaderRoute: typeof CourtsCourtSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourtsCourtSlugRoute: CourtsCourtSlugRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  CourtsIndexRoute: CourtsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
