/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TickertestRouteImport } from './routes/tickertest'
import { Route as TickersRouteImport } from './routes/tickers'
import { Route as QuickMatchRouteImport } from './routes/quick-match'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistryIndexRouteImport } from './routes/registry.index'
import { Route as CourtsIndexRouteImport } from './routes/courts.index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as CourtsCourtSlugIndexRouteImport } from './routes/courts.$courtSlug.index'
import { Route as CourtsCourtSlugTickerRouteImport } from './routes/courts.$courtSlug.ticker'
import { Route as CourtsCourtSlugScoreboardRouteImport } from './routes/courts.$courtSlug.scoreboard'
import { Route as CourtsCourtSlugRefereeRouteImport } from './routes/courts.$courtSlug.referee'
import { Route as CourtsCourtSlugOverlayConsoleRouteImport } from './routes/courts.$courtSlug.overlay-console'

const TickertestRoute = TickertestRouteImport.update({
  id: '/tickertest',
  path: '/tickertest',
  getParentRoute: () => rootRouteImport,
} as any)
const TickersRoute = TickersRouteImport.update({
  id: '/tickers',
  path: '/tickers',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickMatchRoute = QuickMatchRouteImport.update({
  id: '/quick-match',
  path: '/quick-match',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryIndexRoute = RegistryIndexRouteImport.update({
  id: '/registry/',
  path: '/registry/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsIndexRoute = CourtsIndexRouteImport.update({
  id: '/courts/',
  path: '/courts/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsCourtSlugIndexRoute = CourtsCourtSlugIndexRouteImport.update({
  id: '/courts/$courtSlug/',
  path: '/courts/$courtSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsCourtSlugTickerRoute = CourtsCourtSlugTickerRouteImport.update({
  id: '/courts/$courtSlug/ticker',
  path: '/courts/$courtSlug/ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsCourtSlugScoreboardRoute =
  CourtsCourtSlugScoreboardRouteImport.update({
    id: '/courts/$courtSlug/scoreboard',
    path: '/courts/$courtSlug/scoreboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourtsCourtSlugRefereeRoute = CourtsCourtSlugRefereeRouteImport.update({
  id: '/courts/$courtSlug/referee',
  path: '/courts/$courtSlug/referee',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtsCourtSlugOverlayConsoleRoute =
  CourtsCourtSlugOverlayConsoleRouteImport.update({
    id: '/courts/$courtSlug/overlay-console',
    path: '/courts/$courtSlug/overlay-console',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quick-match': typeof QuickMatchRoute
  '/tickers': typeof TickersRoute
  '/tickertest': typeof TickertestRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts/': typeof CourtsIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/courts/$courtSlug/overlay-console': typeof CourtsCourtSlugOverlayConsoleRoute
  '/courts/$courtSlug/referee': typeof CourtsCourtSlugRefereeRoute
  '/courts/$courtSlug/scoreboard': typeof CourtsCourtSlugScoreboardRoute
  '/courts/$courtSlug/ticker': typeof CourtsCourtSlugTickerRoute
  '/courts/$courtSlug/': typeof CourtsCourtSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quick-match': typeof QuickMatchRoute
  '/tickers': typeof TickersRoute
  '/tickertest': typeof TickertestRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts': typeof CourtsIndexRoute
  '/registry': typeof RegistryIndexRoute
  '/courts/$courtSlug/overlay-console': typeof CourtsCourtSlugOverlayConsoleRoute
  '/courts/$courtSlug/referee': typeof CourtsCourtSlugRefereeRoute
  '/courts/$courtSlug/scoreboard': typeof CourtsCourtSlugScoreboardRoute
  '/courts/$courtSlug/ticker': typeof CourtsCourtSlugTickerRoute
  '/courts/$courtSlug': typeof CourtsCourtSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quick-match': typeof QuickMatchRoute
  '/tickers': typeof TickersRoute
  '/tickertest': typeof TickertestRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/courts/': typeof CourtsIndexRoute
  '/registry/': typeof RegistryIndexRoute
  '/courts/$courtSlug/overlay-console': typeof CourtsCourtSlugOverlayConsoleRoute
  '/courts/$courtSlug/referee': typeof CourtsCourtSlugRefereeRoute
  '/courts/$courtSlug/scoreboard': typeof CourtsCourtSlugScoreboardRoute
  '/courts/$courtSlug/ticker': typeof CourtsCourtSlugTickerRoute
  '/courts/$courtSlug/': typeof CourtsCourtSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quick-match'
    | '/tickers'
    | '/tickertest'
    | '/match/$matchId'
    | '/courts/'
    | '/registry/'
    | '/courts/$courtSlug/overlay-console'
    | '/courts/$courtSlug/referee'
    | '/courts/$courtSlug/scoreboard'
    | '/courts/$courtSlug/ticker'
    | '/courts/$courtSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quick-match'
    | '/tickers'
    | '/tickertest'
    | '/match/$matchId'
    | '/courts'
    | '/registry'
    | '/courts/$courtSlug/overlay-console'
    | '/courts/$courtSlug/referee'
    | '/courts/$courtSlug/scoreboard'
    | '/courts/$courtSlug/ticker'
    | '/courts/$courtSlug'
  id:
    | '__root__'
    | '/'
    | '/quick-match'
    | '/tickers'
    | '/tickertest'
    | '/match/$matchId'
    | '/courts/'
    | '/registry/'
    | '/courts/$courtSlug/overlay-console'
    | '/courts/$courtSlug/referee'
    | '/courts/$courtSlug/scoreboard'
    | '/courts/$courtSlug/ticker'
    | '/courts/$courtSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuickMatchRoute: typeof QuickMatchRoute
  TickersRoute: typeof TickersRoute
  TickertestRoute: typeof TickertestRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  CourtsIndexRoute: typeof CourtsIndexRoute
  RegistryIndexRoute: typeof RegistryIndexRoute
  CourtsCourtSlugOverlayConsoleRoute: typeof CourtsCourtSlugOverlayConsoleRoute
  CourtsCourtSlugRefereeRoute: typeof CourtsCourtSlugRefereeRoute
  CourtsCourtSlugScoreboardRoute: typeof CourtsCourtSlugScoreboardRoute
  CourtsCourtSlugTickerRoute: typeof CourtsCourtSlugTickerRoute
  CourtsCourtSlugIndexRoute: typeof CourtsCourtSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickertest': {
      id: '/tickertest'
      path: '/tickertest'
      fullPath: '/tickertest'
      preLoaderRoute: typeof TickertestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickers': {
      id: '/tickers'
      path: '/tickers'
      fullPath: '/tickers'
      preLoaderRoute: typeof TickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-match': {
      id: '/quick-match'
      path: '/quick-match'
      fullPath: '/quick-match'
      preLoaderRoute: typeof QuickMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry/': {
      id: '/registry/'
      path: '/registry'
      fullPath: '/registry/'
      preLoaderRoute: typeof RegistryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/': {
      id: '/courts/'
      path: '/courts'
      fullPath: '/courts/'
      preLoaderRoute: typeof CourtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$courtSlug/': {
      id: '/courts/$courtSlug/'
      path: '/courts/$courtSlug'
      fullPath: '/courts/$courtSlug/'
      preLoaderRoute: typeof CourtsCourtSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$courtSlug/ticker': {
      id: '/courts/$courtSlug/ticker'
      path: '/courts/$courtSlug/ticker'
      fullPath: '/courts/$courtSlug/ticker'
      preLoaderRoute: typeof CourtsCourtSlugTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$courtSlug/scoreboard': {
      id: '/courts/$courtSlug/scoreboard'
      path: '/courts/$courtSlug/scoreboard'
      fullPath: '/courts/$courtSlug/scoreboard'
      preLoaderRoute: typeof CourtsCourtSlugScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$courtSlug/referee': {
      id: '/courts/$courtSlug/referee'
      path: '/courts/$courtSlug/referee'
      fullPath: '/courts/$courtSlug/referee'
      preLoaderRoute: typeof CourtsCourtSlugRefereeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courts/$courtSlug/overlay-console': {
      id: '/courts/$courtSlug/overlay-console'
      path: '/courts/$courtSlug/overlay-console'
      fullPath: '/courts/$courtSlug/overlay-console'
      preLoaderRoute: typeof CourtsCourtSlugOverlayConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuickMatchRoute: QuickMatchRoute,
  TickersRoute: TickersRoute,
  TickertestRoute: TickertestRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  CourtsIndexRoute: CourtsIndexRoute,
  RegistryIndexRoute: RegistryIndexRoute,
  CourtsCourtSlugOverlayConsoleRoute: CourtsCourtSlugOverlayConsoleRoute,
  CourtsCourtSlugRefereeRoute: CourtsCourtSlugRefereeRoute,
  CourtsCourtSlugScoreboardRoute: CourtsCourtSlugScoreboardRoute,
  CourtsCourtSlugTickerRoute: CourtsCourtSlugTickerRoute,
  CourtsCourtSlugIndexRoute: CourtsCourtSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
